### ISSUE TITLE
Failed to delete the uploaded file (unexpected error)

### ISSUE THREAD

**Issue by Andrewcomply** [equinoxventures/cytomine-bootstrap#1]
When attempting to 'delete' a file within storage, this error appeared

<img width="1104" alt="Screen Shot 2022-10-04 at 1 28 29 pm" src="https://user-images.githubusercontent.com/111470720/193979492-afb2b950-b71d-459e-aec3-d66a6237683e.png">

**Comment by vewe-richard** [comment]
I guess, we can not delete uploaded file, we can delete deployed files.
Can you find a way to reproduce this problem?

**Comment by vewe-richard** [comment]
![image](https://user-images.githubusercontent.com/13496173/196066034-56931900-698b-4220-93e3-bf8413cbc24a.png)

**Comment by vewe-richard** [comment]
Continue ...
sudo docker logs -f core
29-10-2022 00:59:22,631  WARN ConstraintException - This slice be.cytomine.image.AbstractSlice : 2418 cannot be deleted as it has already been insert in projects [test2]
29-10-2022 00:59:22,631 ERROR RestController - This slice be.cytomine.image.AbstractSlice : 2418 cannot be deleted as it has already been insert in projects [test2]

**Comment by vewe-richard** [comment]
https://github.com/cytomine/Cytomine-core/blob/a64523e157a57605c7274f1bcd051ca516b483ae/grails-app/services/be/cytomine/image/AbstractSliceService.groovy#L79

**Comment by vewe-richard** [comment]
Now, we can reproduce this problem.
Just upload an image and link with one project
After that, go to the project, delete this image, and go out to storage page, try to delete this image and got the error

**Comment by vewe-richard** [comment]
How to debug this issue? How to debug core?

# build docker for development from core
` $ cat work/grails/build/dockerfile 
FROM cytomine/core:v3.2.3

RUN apt-get update
RUN apt-get install -y iproute2 iputils-ping
RUN apt-get install -y bridge-utils
RUN apt-get install -y net-tools netcat tcpdump vim

COPY deploy.sh /tmp/deploy.sh
$ cat work/grails/build/deploy.sh 
#!/bin/bash
/bin/sleep 3000000`

build the image as jiangjqian/grails4 for example,
# Run the docker
`
bash start_deploy.sh
docker stop core
docker rm core
sudo docker run -d --name core --link postgresql:postgresql --link mongodb:mongodb --link rabbitmq:rab
bitmq -v /etc/localtime:/etc/localtime -v /data/softwares/code:/data/softwares/code jiangjqian/grails4
`
# Enter docker to config

```
sudo docker exec -it core /bin/bash
# get grails 2.4.4
# write start.sh as,
~/grails-2.4.4# cat start.sh            
export GRAILS_HOME=/root/grails-2.4.4                     
export GRAILS_OPTS="-Xmx2G -Xms512m -XX:MaxPermSize=512m" 
export PATH="$PATH:$GRAILS_HOME/bin"                      

source start.sh
```

# Run cytomine core
```
cd /root/Cytomine-core
$ grails
$ run-war
```

**Comment by vewe-richard** [comment]
Next, need find the way to gdb it.

**Comment by vewe-richard** [comment]
Run core in a more straight way,
```
git clone https://github.com/cytomine/Cytomine-core.git
cd Cytomine-core
./grailsw
```
There normally will emit an error, that can not access 
wrapper.dist.url=http://dist.springframework.org.s3.amazonaws.com/release/GRAILS/

Need setup an nginx container, and copy 
"cp grails-2.4.4.zip /usr/share/nginx/html/"

Then come back to core container, change code ./wrapper/grails-wrapper.properties to,
wrapper.dist.url=http://172.17.0.1:8080/

**Comment by vewe-richard** [comment]
Report 3 issues to community, 

https://github.com/cytomine/Cytomine-core/issues/1227
https://github.com/cytomine/Cytomine-core/issues/1226
https://github.com/cytomine/Cytomine-core/issues/1225

How to run this application and debug it directly?

**Comment by travis-comply** [comment]
Hey @vewe-richard were you able to make any more progress on this? I have found out that I am running into a similar issue where i have deleted a file from a `Project` but i am unable to delete it from the `Storage`
![Screen Shot 2022-12-14 at 10 44 02 am](https://user-images.githubusercontent.com/99149610/207469579-ba76f362-c5d5-4631-b2c4-958296e26719.png)
![Screen Shot 2022-12-14 at 10 44 46 am (2)](https://user-images.githubusercontent.com/99149610/207469610-7992f2e6-2b70-413d-8c93-8bdbe753586f.png)

**Comment by vewe-richard** [comment]
@travis-comply Yes, it's fixed. You can verify and close this issue.
