### ISSUE TITLE
Analysis status failed

### ISSUE THREAD

**Issue by Andrewcomply** [equinoxventures/cytomine-bootstrap#12]
status failed on demo for the analysis

<img width="815" alt="Screen Shot 2022-10-19 at 8 21 36 pm" src="https://user-images.githubusercontent.com/111470720/196818518-4fae4e5c-44e9-468c-aa65-2738be5e93c5.png">

**Comment by vewe-richard** [comment]
fixed, similar as bellow issue
https://github.com/equinoxventures/cytomine-bootstrap/issues/11
