### ISSUE TITLE
Login and Log in as user issue

### ISSUE THREAD

**Issue by travis-comply** [equinoxventures/cytomine-bootstrap#17]
When logging into Cytomine, the page does not always correctly refresh and log you in. Instead it keeps you on the log in screen with no error message or page refresh.

This issue appears in the console of the browser (tested on Chrome and Firefox): 
![Screen Shot 2022-12-02 at 3 49 54 pm](https://user-images.githubusercontent.com/99149610/205217759-d857d8a2-d488-40d9-b0c7-3c1e5474df08.png)

After logging out to test again the page appears to refresh, but after waiting on the page for about five seconds.

There is also an issue as an admin when trying to log in as a user. It does work but initially, it presents this error 
![Screen Shot 2022-12-02 at 3 50 42 pm](https://user-images.githubusercontent.com/99149610/205217873-576c73c9-326e-40f2-a3c2-1e543e56b6be.png)
but once you refresh the page you have now been logged in as the selected user.

**Comment by vewe-richard** [comment]
Yes, it's too long to wait.
And without error message if wrong user name or password

**Comment by travis-comply** [comment]
completed on 5/12 - tested and approved
