### ISSUE TITLE
Unable to delete and lock a user

### ISSUE THREAD

**Issue by Andrewcomply** [equinoxventures/cytomine-bootstrap#2]
Some questions that you might want to take a look into:

1. I am currently an admin. Why can't I "lock" a user? And what does the "Lock" do?
2. How do I delete/remove a user?

![Screen Shot 2022-10-05 at 1 57 29 pm](https://user-images.githubusercontent.com/111470720/193979170-0226d041-8893-4bb0-af81-afb4527c3f6e.png)

**Comment by vewe-richard** [comment]
![image](https://user-images.githubusercontent.com/13496173/194826365-6eaffe29-ed70-44b6-94ba-23009fb218c0.png)
I can lock users.

**Comment by vewe-richard** [comment]
I got the problem, it seems, after a while I can not unlock users.

**Comment by ben-gy** [comment]
ice this issue for now
