### ISSUE TITLE
Not receiving email when new user is added

### ISSUE THREAD

**Issue by Andrewcomply** [equinoxventures/cytomine-bootstrap#3]
I've added new users Ben and Myself as guest users but I did not receive an email in my inbox or spam folders in my gmail. please review video here https://www.loom.com/share/10b07d589a054d858999de5dc1709511

**Comment by vewe-richard** [comment]
ADMIN_EMAIL='ben@labflow.ai'
# SENDER_EMAIL, SENDER_EMAIL_PASS, SENDER_EMAIL_SMTP : email params of the sending account
SENDER_EMAIL_PASS='dfcbba6c-9b30-4147-9509-52f8e1f60d09'
SENDER_EMAIL_SMTP_HOST='smpt.postmarkapp.com'
SENDER_EMAIL_SMTP_PORT='587'
SENDER_EMAIL='noreply@labflow.ai'
# RECEIVER_EMAIL : email adress of the receiver
RECEIVER_EMAIL='backup@labflow.ai'

**Comment by ben-gy** [comment]
Hey @vewe-richard - have these been implemented?

**Comment by vewe-richard** [comment]
@ben-gy Implemented.
