### ISSUE TITLE
Error message upon deleting file: "This image has instances in active projects"

### ISSUE THREAD

**Issue by Andrewcomply** [equinoxventures/cytomine-bootstrap#5]
When attempting to 'delete' a file within storage, this error appeared

<img width="1104" alt="Screen Shot 2022-10-04 at 1 28 15 pm" src="https://user-images.githubusercontent.com/111470720/193979570-31a1e103-07a3-43dd-b045-d67415f7f5ff.png">

**Comment by vewe-richard** [comment]
It's not a problem.
You have to delete an image file in the project scope.
